import React from 'react';
import Header from '../../components/Header/Header';
import Head from 'next/head';
import Slider from '../../components/Features/Slider';
import Highlights from '../../components/Highlights/Highlights';
import CarIntro from '../../components/CarIntro/CarIntro';
import { getModel, getModels } from '../../services/publicHandle';

export async function getStaticProps(context) {
  const { params } = context;
  const req = await getModel(params.modelID);
  const data = req.data;

  if (!data?.id) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      model: data,
    },
  };
}

export async function getStaticPaths() {
  const req = await getModels();
  const models = req.data;
  const paths = models.map(model => {
    return {
      params: { modelID: `${model.id}` },
    };
  });

  return {
    paths,
    fallback: false,
  };
}

const FeaturesScreen = ({ model }) => {
  return (
    <>
      <Head>
        <title>Modelo {model.id}</title>
        {/* <meta name='description' content='Generated by create next app' /> */}
      </Head>
      <Header />
      <article className='mt-[43px] lg:mt-[80px] flex flex-col'>
        <section>
          <CarIntro model={model} />
        </section>
        <section className='py-[50px] mt-[38px] md:mt-[80px] relative bg-[#F7F7F7]'>
          <Slider model={model} />
        </section>
        <section className='my-[44px] md:my-[66.6px]'>
          <Highlights model={model} />
        </section>
      </article>
    </>
  );
};

export default FeaturesScreen;
