import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>EGO Challenge</title>
        {/* <meta name='description' content='Generated by create next app' />  TODO: Include SEO metatags*/}
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* For this challenge, index will redirect to /modelos (see pages/_middleware.js) */}
    </>
  );
}
